[tool.semantic_release]
version_variables = [
  "bamboopass/version.py:__version__",
  "pyproject.toml:project.version",
]
tag_format = "v{version}"
commit_message = "chore(release): v{version}"
build_command = ""
